services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: fabt_user
      POSTGRES_PASSWORD: fabt_password
      POSTGRES_DB: fabt_db
    ports:
      - "5432:5432"
    volumes:
      - fabt_pg_data:/var/lib/postgresql/data

volumes:
  fabt_pg_data:
